'use strict';
const $=id=>document.getElementById(id);const clamp=(n,a,b)=>Math.min(Math.max(n,a),b);const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};const pct=n=>Number.isFinite(n)?(n*100).toFixed(1)+'%':'—';const money=n=>(n<0?'-':'')+'€'+Math.abs(n||0).toFixed(2);
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function todayLocal(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}

const Cache={prefix:'betsify_api_',get(k){try{const x=JSON.parse(localStorage.getItem(this.prefix+k));if(!x||Date.now()>x.expires){localStorage.removeItem(this.prefix+k);return null}return x.data}catch{return null}},set(k,data,ttl){try{localStorage.setItem(this.prefix+k,JSON.stringify({data,expires:Date.now()+ttl}))}catch{}this.render()},clear(){Object.keys(localStorage).filter(k=>k.startsWith(this.prefix)).forEach(k=>localStorage.removeItem(k));this.render()},render(){$('cache-count').textContent=Object.keys(localStorage).filter(k=>k.startsWith(this.prefix)).length}};
const API={base:'https://v3.football.api-sports.io',status:'idle',getKey(){return localStorage.getItem('betsify_api_key')||''},setKey(k){localStorage.setItem('betsify_api_key',k.trim())},async request(path,params={},ttl=0){const key=this.getKey();if(!key)throw new Error('Falta la API key');const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!==null&&v!==undefined).map(([k,v])=>[k,String(v)]));const cacheKey=path+'?'+q.toString();if(ttl){const hit=Cache.get(cacheKey);if(hit)return hit}const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),12000);let res;try{res=await fetch(this.base+path+'?'+q,{headers:{'x-apisports-key':key,'Accept':'application/json'},signal:ctrl.signal})}finally{clearTimeout(timer)}const daily=res.headers.get('x-ratelimit-requests-remaining');const minute=res.headers.get('x-ratelimit-remaining');if(daily!==null)$('quota-daily').textContent=daily;if(minute!==null)$('quota-minute').textContent=minute;let body;try{body=await res.json()}catch{throw new Error('Respuesta no válida de API-Football')}const errors=body?.errors;const hasErrors=Array.isArray(errors)?errors.length>0:errors&&Object.keys(errors).length>0;if(!res.ok||hasErrors){const detail=Array.isArray(errors)?errors.join(', '):Object.values(errors||{}).join(', ');throw new Error(detail||('HTTP '+res.status))}this.status='ok';const data=body.response;if(ttl)Cache.set(cacheKey,data,ttl);return data},fixtures(date,league){return this.request('/fixtures',{date,league:league||undefined,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone},15*60e3)},teamStats(league,season,team){return this.request('/teams/statistics',{league,season,team},12*60*60e3)},prediction(fixture){return this.request('/predictions',{fixture},60*60e3)},odds(fixture){return this.request('/odds',{fixture},2*60*60e3)},test(){return this.request('/status',{},0)}};

const State={fixtures:[],fixture:null,model:null,apiPrediction:null,odds:null,bankroll:num(localStorage.getItem('edge2026_bankroll'))||num(localStorage.getItem('betsify_bankroll'))||0,bets:JSON.parse(localStorage.getItem('edge2026_bets')||localStorage.getItem('betsify_bets')||'[]')};
function saveBets(){localStorage.setItem('betsify_bets',JSON.stringify(State.bets))}function saveBankroll(){localStorage.setItem('betsify_bankroll',String(State.bankroll))}

function poisson(l,k){if(l<=0)return k===0?1:0;let lp=-l+k*Math.log(l);for(let i=1;i<=k;i++)lp-=Math.log(i);return Math.exp(lp)}
function grid(lh,la){const a=[];let total=0;for(let h=0;h<=9;h++)for(let v=0;v<=9;v++){const p=poisson(lh,h)*poisson(la,v);a.push({h,v,p});total+=p}return a.map(x=>({...x,p:x.p/total}))}
function derive(g){let h=0,d=0,a=0,over=0,btts=0;for(const x of g){if(x.h>x.v)h+=x.p;else if(x.h===x.v)d+=x.p;else a+=x.p;if(x.h+x.v>2.5)over+=x.p;if(x.h>0&&x.v>0)btts+=x.p}return{h,d,a,over,under:1-over,btts,noBtts:1-btts}}
function normalize3(x){const s=x.h+x.d+x.a;return s?{h:x.h/s,d:x.d/s,a:x.a/s}:{h:1/3,d:1/3,a:1/3}}
function parseApiPercent(pred){const p=pred?.predictions?.percent;if(!p)return null;const h=num(String(p.home??'').replace('%','')),d=num(String(p.draw??'').replace('%','')),a=num(String(p.away??'').replace('%',''));if(h===null||d===null||a===null)return null;return normalize3({h:h/100,d:d/100,a:a/100})}
function safeAverage(v,fallback){const n=num(v);return n!==null&&n>0?n:fallback}
function buildTeamSummary(fixture,stats,isHome){const side=isHome?'home':'away';const team=fixture.teams[side];const played=stats?.fixtures?.played?.total||0;const gf=safeAverage(stats?.goals?.for?.average?.total,1.25);const ga=safeAverage(stats?.goals?.against?.average?.total,1.25);return{name:team.name,logo:team.logo,id:team.id,played,gf,ga,wins:stats?.fixtures?.wins?.total||0,draws:stats?.fixtures?.draws?.total||0,losses:stats?.fixtures?.loses?.total||0,form:stats?.form||'—'}}
function buildModel(home,away,pred){const leagueMean=1.25;let lh=(home.gf*.58+away.ga*.42)*1.08;let la=(away.gf*.58+home.ga*.42)*.96;lh=lh*.82+leagueMean*.18;la=la*.82+leagueMean*.18;const pg=pred?.predictions?.goals;const apiGh=num(pg?.home),apiGa=num(pg?.away);if(apiGh!==null)lh=lh*.78+apiGh*.22;if(apiGa!==null)la=la*.78+apiGa*.22;lh=clamp(lh,.15,4.5);la=clamp(la,.15,4.5);const poissonProb=normalize3(derive(grid(lh,la)));const apiProb=parseApiPercent(pred);const final=apiProb?normalize3({h:poissonProb.h*.75+apiProb.h*.25,d:poissonProb.d*.75+apiProb.d*.25,a:poissonProb.a*.75+apiProb.a*.25}):poissonProb;const markets=derive(grid(lh,la));return{lh,la,poisson:poissonProb,api:apiProb,final,markets}}

function renderFixtureOptions(){const s=$('fixture-select');s.innerHTML='<option value="">— Elige un partido —</option>'+State.fixtures.map((f,i)=>{const t=new Date(f.fixture.date).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});return `<option value="${i}">${t} · ${esc(f.teams.home.name)} vs ${esc(f.teams.away.name)} · ${esc(f.league.name)}</option>`}).join('');s.disabled=!State.fixtures.length;$('analyze-fixture').disabled=true}
async function loadFixtures(){const date=$('fixture-date').value;const league=num($('league-id').value);if(!API.getKey()){setApiMessage('Añade primero tu API key en la pestaña API.','err');return}const b=$('load-fixtures');b.disabled=true;b.textContent='Cargando…';try{State.fixtures=await API.fixtures(date,league);renderFixtureOptions();setApiMessage(State.fixtures.length?`${State.fixtures.length} partidos cargados para ${date}.`:'No hay partidos para estos filtros.',State.fixtures.length?'ok':'');}catch(e){setApiMessage('Error: '+e.message,'err')}finally{b.disabled=false;b.textContent='Cargar partidos'}}
function setApiMessage(text,type=''){const e=$('api-message');e.textContent=text;e.className='status '+type}
function renderTeamCard(t){return `<div class="card"><div class="fixture-team"><img src="${esc(t.logo)}" alt=""><span>${esc(t.name)}</span></div><div class="stat-grid" style="margin-top:12px"><div class="stat"><strong>${t.gf.toFixed(2)}</strong><small>GF/partido</small></div><div class="stat"><strong>${t.ga.toFixed(2)}</strong><small>GC/partido</small></div><div class="stat"><strong>${t.played}</strong><small>Jugados</small></div><div class="stat"><strong class="green">${t.wins}</strong><small>Victorias</small></div><div class="stat"><strong class="yellow">${t.draws}</strong><small>Empates</small></div><div class="stat"><strong class="red">${t.losses}</strong><small>Derrotas</small></div></div><div class="note" style="margin-top:9px">Forma: ${esc(t.form)}</div></div>`}
function renderComparison(m){const r=(label,p)=>`<div>${label}</div><div class="green">${p?pct(p.h):'—'}</div><div class="yellow">${p?pct(p.d):'—'}</div><div class="blue">${p?pct(p.a):'—'}</div>`;$('model-comparison').innerHTML='<div class="head">Modelo</div><div class="head">1</div><div class="head">X</div><div class="head">2</div>'+r('Poisson Betsify',m.poisson)+r('API-Football',m.api)+r('Ensemble final',m.final)}
function renderMarkets(){const m=State.model.markets;const p=State.model.final;const defs=[['1X2','odd-home','Local',p.h,'odd-draw','Empate',p.d,'odd-away','Visitante',p.a],['Goles 2.5','odd-over','Over 2.5',m.over,'odd-under','Under 2.5',m.under],['Ambos marcan','odd-btts-yes','Sí',m.btts,'odd-btts-no','No',m.noBtts]];$('markets').innerHTML=defs.map(d=>`<div class="market"><div class="market-head"><strong>${d[0]}</strong></div><div class="market-inputs">${Array.from({length:(d.length-1)/3},(_,i)=>{const j=1+i*3;return `<div><label>${d[j+1]} · ${pct(d[j+2])}</label><input type="number" min="1.01" step=".01" id="${d[j]}" placeholder="Cuota"></div>`}).join('')}</div></div>`).join('');fillOdds(State.odds)}
function bestOdds(raw){const result={};for(const event of raw||[])for(const bk of event.bookmakers||[])for(const bet of bk.bets||[]){const name=String(bet.name||'').toLowerCase();for(const v of bet.values||[]){const value=String(v.value||'').toLowerCase();const odd=num(v.odd);if(!odd)continue;let key=null;if(name.includes('match winner'))key=value==='home'?'home':value==='draw'?'draw':value==='away'?'away':null;else if(name.includes('goals over/under')||name.includes('over/under'))key=value==='over 2.5'?'over':value==='under 2.5'?'under':null;else if(name.includes('both teams')||name.includes('both team'))key=value==='yes'?'bttsYes':value==='no'?'bttsNo':null;if(key&&(!result[key]||odd>result[key].odd))result[key]={odd,bk:bk.name}}}return result}
function fillOdds(raw){const o=bestOdds(raw);const map={home:'odd-home',draw:'odd-draw',away:'odd-away',over:'odd-over',under:'odd-under',bttsYes:'odd-btts-yes',bttsNo:'odd-btts-no'};for(const[k,id]of Object.entries(map))if(o[k]&&$(id))$(id).value=o[k].odd;const bks=[...new Set(Object.values(o).map(x=>x.bk))];$('odds-source').textContent=bks.length?'Mejores cuotas encontradas entre: '+bks.join(', '):'No se encontraron cuotas compatibles; puedes introducirlas manualmente.'}
async function analyzeFixture(){const idx=num($('fixture-select').value);if(idx===null||!State.fixtures[idx])return;State.fixture=State.fixtures[idx];const f=State.fixture,b=$('analyze-fixture');b.disabled=true;b.textContent='Analizando…';setApiMessage('Consultando estadísticas, predicción y cuotas…');try{const [hs,as,pred,odds]=await Promise.all([API.teamStats(f.league.id,f.league.season,f.teams.home.id),API.teamStats(f.league.id,f.league.season,f.teams.away.id),API.prediction(f.fixture.id).catch(()=>[]),API.odds(f.fixture.id).catch(()=>[])]);const hp=Array.isArray(pred)?pred[0]:null;State.apiPrediction=hp;State.odds=odds;const home=buildTeamSummary(f,hs,true),away=buildTeamSummary(f,as,false);State.model=buildModel(home,away,hp);renderAnalysis(f,home,away);setApiMessage('Análisis actualizado con API-Football.','ok')}catch(e){setApiMessage('No se pudo completar el análisis: '+e.message,'err')}finally{b.disabled=false;b.textContent='Analizar fixture'}}
function renderAnalysis(f,h,a){$('analysis-output').classList.remove('hidden');const dt=new Date(f.fixture.date).toLocaleString('es-ES',{dateStyle:'medium',timeStyle:'short'});$('fixture-card').innerHTML=`<div class="section-label">${esc(f.league.name)} · ${esc(f.league.round||'')}</div><div class="grid grid-2"><div class="fixture-team"><img src="${esc(f.teams.home.logo)}"><span>${esc(f.teams.home.name)}</span></div><div class="fixture-team" style="justify-content:flex-end"><span>${esc(f.teams.away.name)}</span><img src="${esc(f.teams.away.logo)}"></div></div><div class="fixture-meta"><span>${dt}</span><span>${esc(f.fixture.venue?.name||'Sede por confirmar')}</span><span>Fixture #${f.fixture.id}</span></div>`;$('team-cards').innerHTML=renderTeamCard(h)+renderTeamCard(a);const p=State.model.final;$('prob-home-name').textContent=h.name;$('prob-away-name').textContent=a.name;$('prob-home').textContent=pct(p.h);$('prob-draw').textContent=pct(p.d);$('prob-away').textContent=pct(p.a);$('bar-home').style.width=p.h*100+'%';$('bar-draw').style.width=p.d*100+'%';$('bar-away').style.width=p.a*100+'%';$('lambda-line').textContent=`Goles esperados del modelo: ${h.name} ${State.model.lh.toFixed(2)} — ${a.name} ${State.model.la.toFixed(2)}. No son xG oficiales.`;renderComparison(State.model);$('api-advice').textContent=State.apiPrediction?.predictions?.advice?'API-Football: '+State.apiPrediction.predictions.advice:'API-Football no ofrece predicción para este fixture.';renderMarkets();$('ev-card').classList.add('hidden');$('bet-match').value=h.name+' vs '+a.name;$('analysis-output').scrollIntoView({behavior:'smooth',block:'start'})}
function calculateEV(){if(!State.model)return;const g=id=>num($(id)?.value);const items=[['1 · Local',State.model.final.h,g('odd-home')],['X · Empate',State.model.final.d,g('odd-draw')],['2 · Visitante',State.model.final.a,g('odd-away')],['Over 2.5',State.model.markets.over,g('odd-over')],['Under 2.5',State.model.markets.under,g('odd-under')],['BTTS Sí',State.model.markets.btts,g('odd-btts-yes')],['BTTS No',State.model.markets.noBtts,g('odd-btts-no')]].filter(x=>x[2]&&x[2]>=1.01).map(x=>({...{name:x[0],prob:x[1],odds:x[2]},ev:x[1]*x[2]-1,fair:1/x[1]})).sort((a,b)=>b.ev-a.ev);if(!items.length){toast('Introduce al menos una cuota');return}$('ev-list').innerHTML=items.map(x=>`<div class="ev-row"><div><div class="ev-name">${esc(x.name)}</div><div class="ev-sub">Prob. ${pct(x.prob)} · justa ${x.fair.toFixed(2)} · mercado ${x.odds.toFixed(2)}</div></div><span class="chip ${x.ev>=.05?'pos':x.ev>=0?'mid':'neg'}">${x.ev>=0?'+':''}${(x.ev*100).toFixed(1)}% EV</span></div>`).join('');$('ev-card').classList.remove('hidden')}

function settledStats(){const settled=State.bets.filter(b=>['win','loss','void'].includes(b.result));let invested=0,returns=0;for(const b of settled){if(b.result==='void')continue;invested+=b.stake;if(b.result==='win')returns+=b.stake*b.odds}return{invested,profit:returns-invested,roi:invested?(returns-invested)/invested:0}}
function renderBankroll(){const s=settledStats();$('bankroll-value').textContent=money(State.bankroll);$('bankroll-input').value=State.bankroll||'';$('sum-invested').textContent=money(s.invested);$('sum-profit').textContent=money(s.profit);$('sum-profit').className=s.profit>=0?'green':'red';$('sum-roi').textContent=(s.roi>=0?'+':'')+(s.roi*100).toFixed(1)+'%';$('sum-roi').className=s.roi>=0?'green':'red'}
function renderBets(){const c=$('bets-list');if(!State.bets.length){c.innerHTML='<div class="card note">Todavía no hay apuestas registradas.</div>';renderBankroll();return}c.innerHTML=State.bets.map(b=>`<div class="bet"><div class="bet-top"><div><div class="bet-title">${esc(b.match)}</div><div class="bet-sub">${esc(b.market)} · ${esc(b.date||'')}</div></div><div style="text-align:right"><strong>${Number(b.odds).toFixed(2)}</strong><div class="bet-sub">${money(b.stake)}</div></div></div><div class="bet-actions">${b.result==='pending'?`<button class="btn btn-sm btn-primary" onclick="setBetResult(${b.id},'win')">WIN</button><button class="btn btn-sm btn-danger" onclick="setBetResult(${b.id},'loss')">LOSS</button><button class="btn btn-sm btn-secondary" onclick="setBetResult(${b.id},'void')">VOID</button>`:`<span class="chip ${b.result==='win'?'pos':b.result==='loss'?'neg':'mid'}">${b.result.toUpperCase()}</span>`}<button class="btn btn-sm btn-secondary" onclick="deleteBet(${b.id})" style="margin-left:auto">Eliminar</button></div></div>`).join('');renderBankroll()}
window.setBetResult=(id,result)=>{const b=State.bets.find(x=>x.id===id);if(b){b.result=result;saveBets();renderBets()}};window.deleteBet=id=>{State.bets=State.bets.filter(x=>x.id!==id);saveBets();renderBets()};
function addBet(){const match=$('bet-match').value.trim(),market=$('bet-market').value.trim(),odds=num($('bet-odds').value),stake=num($('bet-stake').value);if(!match||!market||!odds||odds<1.01||!stake||stake<=0){toast('Completa todos los campos');return}State.bets.unshift({id:Date.now(),match,market,odds,stake,result:'pending',date:new Date().toLocaleDateString('es-ES')});saveBets();renderBets();['bet-market','bet-odds','bet-stake'].forEach(id=>$(id).value='');toast('Apuesta añadida')}
function calcKelly(){const p=num($('kelly-prob').value),o=num($('kelly-odds').value);if(!p||p<=0||p>=100||!o||o<1.01){toast('Datos inválidos');return}const pr=p/100,b=o-1,raw=(b*pr-(1-pr))/b,half=Math.max(0,raw/2),capped=Math.min(.05,half),stake=capped*State.bankroll,ev=pr*o-1;$('kelly-result').innerHTML=ev<=0?`<span class="red">EV ${(ev*100).toFixed(1)}%: no apostar.</span>`:`Stake sugerido: <strong class="green">${money(stake)}</strong> (${(capped*100).toFixed(1)}% del bankroll) · EV +${(ev*100).toFixed(1)}%`}
function updateKeyStatus(text,type=''){const e=$('key-status');e.className='status '+type;e.textContent=text}

function init(){const oldKey=localStorage.getItem('wc26_apikey');if(oldKey&&!API.getKey())API.setKey(oldKey);$('fixture-date').value=todayLocal();$('api-key').value=API.getKey();updateKeyStatus(API.getKey()?'Clave guardada en este navegador.':'Sin API key.');Cache.render();renderBankroll();renderBets();document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+b.dataset.tab))}));$('load-fixtures').addEventListener('click',loadFixtures);$('fixture-select').addEventListener('change',()=>{$('analyze-fixture').disabled=!$('fixture-select').value});$('analyze-fixture').addEventListener('click',analyzeFixture);$('calculate-ev').addEventListener('click',calculateEV);$('save-key').addEventListener('click',()=>{API.setKey($('api-key').value);updateKeyStatus(API.getKey()?'Clave guardada.':'Clave eliminada.',API.getKey()?'ok':'');toast('Configuración guardada')});$('test-key').addEventListener('click',async()=>{updateKeyStatus('Probando conexión…');try{const s=await API.test();updateKeyStatus('Conexión correcta. Plan: '+(s?.subscription?.plan||'desconocido')+'.','ok')}catch(e){updateKeyStatus('Error: '+e.message,'err')}});$('clear-cache').addEventListener('click',()=>{Cache.clear();toast('Caché limpiada')});$('save-bankroll').addEventListener('click',()=>{const v=num($('bankroll-input').value);if(v===null||v<0)return toast('Bankroll inválido');State.bankroll=v;saveBankroll();renderBankroll();toast('Bankroll guardado')});$('calc-kelly').addEventListener('click',calcKelly);$('add-bet').addEventListener('click',addBet)}
init();
