'use strict';
const $=id=>document.getElementById(id), CACHE_KEY='betsify_free_cache_v2';
const cache=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}'), state={events:[],fixture:null,model:null};
const save=()=>localStorage.setItem(CACHE_KEY,JSON.stringify(cache));
const num=v=>{const n=parseFloat(String(v??'').replace('%',''));return Number.isFinite(n)?n:null};
const pct=n=>Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';
$('date').value=new Date().toISOString().slice(0,10);
async function api(params){const r=await fetch('/api/espn?'+new URLSearchParams(params));const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);return j.data}
function competitors(event){const c=event.competitions?.[0]?.competitors||[];return{home:c.find(x=>x.homeAway==='home')||c[0],away:c.find(x=>x.homeAway==='away')||c[1]}}
const teamName=c=>c?.team?.displayName||c?.team?.name||'Equipo';
const teamId=c=>c?.team?.id||c?.id;
const score=c=>num(c?.score?.value??c?.score);
$('load').onclick=async()=>{try{$('fixtureStatus').textContent='Cargando partidos…';const data=await api({mode:'scoreboard',league:'fifa.world',date:$('date').value.replaceAll('-','')});state.events=data.events||[];$('fixture').innerHTML=state.events.map((e,i)=>{const t=competitors(e);return `<option value="${i}">${teamName(t.home)} — ${teamName(t.away)}</option>`}).join('')||'<option>Sin partidos</option>';state.fixture=state.events[0]||null;$('analyze').disabled=!state.fixture;$('fixtureStatus').textContent=state.fixture?`${state.events.length} partidos encontrados.`:'No hay partidos en esa fecha.'}catch(e){$('fixtureStatus').textContent='Error: '+e.message}};
$('fixture').onchange=()=>{state.fixture=state.events[+$('fixture').value]||null;$('analyze').disabled=!state.fixture};
async function schedule(id){const k='schedule:'+id;if(cache[k])return cache[k];const d=await api({mode:'schedule',team:id,season:new Date().getUTCFullYear()});cache[k]=d;save();return d}
async function summary(event){const k='summary:'+event.id;if(cache[k])return cache[k];const d=await api({mode:'summary',event:event.id,league:event.league?.slug||''});cache[k]=d;save();return d}
function statMap(box){const out={};for(const s of box?.statistics||[])out[s.name]=num(s.value??s.displayValue);return out}
const pick=(m,names)=>{for(const n of names)if(m[n]!=null)return m[n];return null};
function parseMatch(event,data,id,index){const cs=event.competitions?.[0]?.competitors||[],own=cs.find(c=>String(teamId(c))===String(id)),opp=cs.find(c=>c!==own),boxes=data.boxscore?.teams||[],ob=boxes.find(b=>String(b.team?.id)===String(id)),xb=boxes.find(b=>String(b.team?.id)===String(teamId(opp))),s=statMap(ob),os=statMap(xb),friendly=(event.league?.slug||'').includes('friendly');return{id:event.id,date:event.date?.slice(0,10),team:teamName(own),opponent:teamName(opp),gf:score(own),ga:score(opp),shots:pick(s,['totalShots','shots']),shotsAgainst:pick(os,['totalShots','shots']),sot:pick(s,['shotsOnTarget']),sotAgainst:pick(os,['shotsOnTarget']),corners:pick(s,['wonCorners','cornerKicks']),cornersAgainst:pick(os,['wonCorners','cornerKicks']),yellow:pick(s,['yellowCards']),red:pick(s,['redCards']),possession:pick(s,['possessionPct']),weight:Math.pow(.9,index)*(friendly?.55:1)}}
async function teamData(id,label){const d=await schedule(id),events=(d.events||[]).filter(e=>e.competitions?.[0]?.status?.type?.completed||e.status?.type?.completed).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,10),rows=[];for(let i=0;i<events.length;i++){$('analysisStatus').textContent=`${label}: procesando ${i+1}/${events.length}…`;try{rows.push(parseMatch(events[i],await summary(events[i]),id,i))}catch{rows.push(parseMatch(events[i],{},id,i))}}return rows}
function weighted(rows,field){let sum=0,w=0,count=0;for(const r of rows)if(r[field]!=null){sum+=r[field]*r.weight;w+=r.weight;count++}return{value:w?sum/w:null,count}}
function aggregate(rows){const a={matches:rows.length};for(const f of ['gf','ga','shots','shotsAgainst','sot','sotAgainst','corners','cornersAgainst','yellow','red','possession']){const x=weighted(rows,f);a[f]=x.value;a[f+'Count']=x.count}return a}
const factorial=n=>{let x=1;for(let i=2;i<=n;i++)x*=i;return x}, pois=(k,l)=>Math.exp(-l)*Math.pow(l,k)/factorial(k);
function model(h,a){let lh=((h.gf??1.2)+(a.ga??1.2))/2,la=((a.gf??1)+(h.ga??1))/2;if(h.sot!=null&&a.sotAgainst!=null)lh*=Math.max(.8,Math.min(1.2,((h.sot+a.sotAgainst)/2)/4.2));if(a.sot!=null&&h.sotAgainst!=null)la*=Math.max(.8,Math.min(1.2,((a.sot+h.sotAgainst)/2)/4.2));lh=Math.max(.2,Math.min(3.5,lh));la=Math.max(.2,Math.min(3.5,la));let home=0,draw=0,away=0,over=0,btts=0;for(let i=0;i<=8;i++)for(let j=0;j<=8;j++){const p=pois(i,lh)*pois(j,la);i>j?home+=p:i===j?draw+=p:away+=p;if(i+j>=3)over+=p;if(i&&j)btts+=p}return{lh,la,home,draw,away,over,btts}}
const stat=(label,value,digits=2)=>`<div class="stat"><span class="muted">${label}</span><b>${value==null?'—':Number(value).toFixed(digits)}</b></div>`;
function renderTeam(id,a){$(id).innerHTML=stat('Goles a favor',a.gf)+stat('Goles en contra',a.ga)+stat('Tiros',a.shots)+stat('A puerta',a.sot)+stat('Córners',a.corners)+stat('Amarillas',a.yellow)+stat('Posesión %',a.possession)+stat('Partidos',a.matches,0)}
$('analyze').onclick=async()=>{if(!state.fixture)return;try{const t=competitors(state.fixture),hn=teamName(t.home),an=teamName(t.away);$('analysisStatus').textContent='Buscando historiales…';const hr=await teamData(teamId(t.home),hn),ar=await teamData(teamId(t.away),an),ha=aggregate(hr),aa=aggregate(ar);state.model=model(ha,aa);$('homeName').textContent=hn;$('awayName').textContent=an;renderTeam('homeStats',ha);renderTeam('awayStats',aa);$('homeCoverage').textContent=`Cobertura: ${ha.shotsCount}/${ha.matches} con tiros; ${ha.cornersCount}/${ha.matches} con córners.`;$('awayCoverage').textContent=`Cobertura: ${aa.shotsCount}/${aa.matches} con tiros; ${aa.cornersCount}/${aa.matches} con córners.`;$('matches').innerHTML=[...hr,...ar].map(r=>`<tr><td>${r.date||'—'}</td><td>${r.team}</td><td>${r.opponent}</td><td>${r.gf??'—'}-${r.ga??'—'}</td><td>${r.shots??'—'}</td><td>${r.sot??'—'}</td><td>${r.corners??'—'}</td><td>${r.yellow??'—'}</td></tr>`).join('');$('labelHome').textContent='Victoria '+hn;$('labelAway').textContent='Victoria '+an;$('teamResults').classList.remove('hidden');$('oddsCard').classList.remove('hidden');$('analysisStatus').textContent=`Listo: ${hr.length} partidos de ${hn} y ${ar.length} de ${an}.`}catch(e){$('analysisStatus').textContent='No se pudo completar: '+e.message}};
$('compare').onclick=()=>{const m=state.model;if(!m)return;const rows=[['Victoria local',m.home,num($('oddHome').value)],['Empate',m.draw,num($('oddDraw').value)],['Victoria visitante',m.away,num($('oddAway').value)],['Over 2.5',m.over,num($('oddOver').value)],['Ambos marcan — Sí',m.btts,num($('oddBtts').value)]];$('modelStats').innerHTML=stat('Goles esperados local',m.lh)+stat('Goles esperados visitante',m.la)+stat('Total esperado',m.lh+m.la)+stat('BTTS %',m.btts*100,1);$('markets').innerHTML=rows.map(([n,p,o])=>{const fair=1/p,ev=o?p*o-1:null;return `<tr><td>${n}</td><td>${pct(p)}</td><td>${fair.toFixed(2)}</td><td>${o?.toFixed(2)||'—'}</td><td class="${ev>0?'good':ev<0?'bad':''}">${ev==null?'—':pct(ev)}</td></tr>`}).join('');$('modelCard').classList.remove('hidden')};
$('clear').onclick=()=>{localStorage.removeItem(CACHE_KEY);location.reload()};$('load').click();
